### ISSUE TITLE
Export all region from segmentation (incl. regions w/o cnv)

### ISSUE THREAD

**Issue by zeochoy** [yuchaojiang/CODEX#2]
Hi Professor, I'm using CODEX for WES without matched normal. It has great result comparing with existing pipeline, which can removed most of the noise. However, I would like to use the segmentation result as another program input (i.e. PureCN for estimating polidy & purity). Is there a way that I may overlook to export all the segmentation result including those regions without any CNV? Thanks very much!

ps. I tried using "fraction" mode. however, the segmentation between samples still varies that seem do not included the copy neutral regions.

**Comment by yuchaojiang** [comment]
Hi,
Sorry for my late reply -- have been traveling and relocating lately. You can use the script below to output all segments including copy-neutral ones.
Cheers,
Yuchao





`
#####################################
# "Interger" mode for germline CNVs
#####################################

finalcall <- segment(Y_qc, Yhat, optK = optK, K = 1:optK, sampname_qc,
                     ref_qc, chr, lmax = 200, mode = "integer")
head(finalcall)
# generate all CNV segments including copy number neutral region.
finalcall.all=finalcall[,1:11]
for(sampi in sampname_qc){
  if(length(which(finalcall[,1]==sampi))==0){
    finalcall.temp=c(sampi,chr,'neutral',start(ref_qc)[1],end(ref_qc)[length(ref_qc)],
      round((end(ref_qc)[length(ref_qc)]-start(ref_qc)[1]+1)/1000,3),1,
      length(ref_qc),sum(Y_qc[,which(sampname_qc==sampi)]),
      sum(Yhat[[optK]][,which(sampname_qc==sampi)]),2)
    finalcall.temp=t(as.matrix(finalcall.temp))
    finalcall.all=rbind(finalcall.all,finalcall.temp)
  } else{
    cn.index=which(finalcall[,1]==sampi)
    st.temp=c(1,as.numeric(finalcall[cn.index,'ed_exon'])+1)
    ed.temp=c(as.numeric(finalcall[cn.index,'st_exon'])-1,length(ref_qc))
    for(t in 1:length(st.temp)){
      finalcall.temp=c(sampi,chr,'neutral',start(ref_qc)[st.temp[t]],end(ref_qc)[ed.temp[t]],
                       round((end(ref_qc)[ed.temp[t]]-start(ref_qc)[st.temp[t]]+1)/1000,3),
                       st.temp[t],ed.temp[t],sum(Y_qc[(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)]),
                       sum(Yhat[[optK]][(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)]),2)
      finalcall.temp=t(as.matrix(finalcall.temp))
      finalcall.all=rbind(finalcall.all,finalcall.temp)
    }
  }
}

finalcall.all=finalcall.all[order(finalcall.all[,1],as.numeric(finalcall.all[,'st_bp'])),]



################################################################
# "Fractional" mode for somatic CNVs from heterogenous samples
################################################################

finalcall <- segment(Y_qc, Yhat, optK = optK, K = 1:optK, sampname_qc,
                     ref_qc, chr, lmax = 200, mode = "fraction")
head(finalcall)
# generate all CNV segments including copy number neutral region.
finalcall.all=finalcall[,1:11]
for(sampi in sampname_qc){
  if(length(which(finalcall[,1]==sampi))==0){
    finalcall.temp=c(sampi,chr,'neutral',start(ref_qc)[1],end(ref_qc)[length(ref_qc)],
                     round((end(ref_qc)[length(ref_qc)]-start(ref_qc)[1]+1)/1000,3),1,
                     length(ref_qc),sum(Y_qc[,which(sampname_qc==sampi)]),
                     sum(Yhat[[optK]][,which(sampname_qc==sampi)]),
                     round(2*sum(Y_qc[,which(sampname_qc==sampi)])/sum(Yhat[[optK]][,which(sampname_qc==sampi)]),3))
    finalcall.temp=t(as.matrix(finalcall.temp))
    finalcall.all=rbind(finalcall.all,finalcall.temp)
  } else{
    cn.index=which(finalcall[,1]==sampi)
    st.temp=c(1,as.numeric(finalcall[cn.index,'ed_exon'])+1)
    ed.temp=c(as.numeric(finalcall[cn.index,'st_exon'])-1,length(ref_qc))
    for(t in 1:length(st.temp)){
      finalcall.temp=c(sampi,chr,'neutral',start(ref_qc)[st.temp[t]],end(ref_qc)[ed.temp[t]],
                       round((end(ref_qc)[ed.temp[t]]-start(ref_qc)[st.temp[t]]+1)/1000,3),
                       st.temp[t],ed.temp[t],sum(Y_qc[(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)]),
                       sum(Yhat[[optK]][(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)]),
                       round(2*sum(Y_qc[(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)])/sum(Yhat[[optK]][(st.temp[t]):(ed.temp[t]),which(sampname_qc==sampi)]),3))
      finalcall.temp=t(as.matrix(finalcall.temp))
      finalcall.all=rbind(finalcall.all,finalcall.temp)
    }
  }
}

finalcall.all=finalcall.all[order(finalcall.all[,1],as.numeric(finalcall.all[,'st_bp'])),]`

**Comment by zeochoy** [comment]
Hi, thanks very much for your help. But I got error while executing the above code. Any hints where it went wrong?
```
Error in Y_qc[(st.temp[t]):(ed.temp[t]), which(sampname_qc == sampi)] : 
  subscript out of bounds
```

**Comment by zeochoy** [comment]
I've figured out where the error come from, and modify the code accordingly within the first few line following the else clause.

```
      cn.index=which(finalcall[,1]==sampi)
      st.temp=c(1,as.numeric(finalcall[cn.index,'ed_exon'])+1)
      st.temp[st.temp > length(ref_qc)] <- length(ref_qc)
      ed.temp=c(as.numeric(finalcall[cn.index,'st_exon'])-1,length(ref_qc))
      ed.temp[ed.temp < 1] <- 1
```
