### ISSUE TITLE
Could not run normalization.

### ISSUE THREAD

**Issue by bishwaG** [yuchaojiang/CODEX#3]
Hi,
I followed the demo code, but got error in normalization step.

```
normObj=normalize2(Y_qc,gc_qc,K=1:4,normal_index=c(2,3,5,7))
k = 1
Error in smooth.spline(gc_qc, z) : 
  'tol' must be strictly positive and finite
In addition: Warning message:
In matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N, byrow = TRUE) :
  data length exceeds size of matrix

```

**Comment by yuchaojiang** [comment]
Did you follow the demo code exactly and get the same output as shown in the vignettes?

Sent from my iPhone

On Nov 7, 2017, at 2:31 AM, bishwaG <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I followed the demo code, but got error in normalization step.

normObj=normalize2(Y_qc,gc_qc,K=1:4,normal_index=c(2,3,5,7))
k = 1
Error in smooth.spline(gc_qc, z) :
  'tol' must be strictly positive and finite
In addition: Warning message:
In matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N, byrow = TRUE) :
  data length exceeds size of matrix

**Comment by bishwaG** [comment]
Sorry my bad. I encountered the error because QC step filtered out everything.
