### ISSUE TITLE
How can I produce mappability for GRCh38?

### ISSUE THREAD

**Issue by bishwaG** [yuchaojiang/CODEX#4]
I would like to generate mappability file for GRCh38. You have advised to set it to 1, but I do not what to do that. How can I do it? Do I need to tweak getmapp() for GRCh38?

**Comment by yuchaojiang** [comment]
Refer to here:

**Comment by yuchaojiang** [comment]
Refer to the links below:

[Mappability pre-calculation](https://github.com/yuchaojiang/CODEX/blob/master/mouse/mapp.R) (Note: This step can be computationally extensive and thus parallel computing is recommended. For CODEX in its default setting, the mappability for exonic targets in human h19 assembly is pre-computed and stored as part of the package).

[Mappability](https://github.com/yuchaojiang/CODEX/blob/master/mouse/getmapp.R)

It's easy if you download mappability from existing database/annotations, e.g., UCSC.

**Comment by bishwaG** [comment]
Thanks for the reply. I tried to download from UCSC table browser, but got little lost. Do I select `group: Repeats `and `track: RepeatMasker`?

**Comment by yuchaojiang** [comment]
Can't help wit this. You need to ask UCSC if needed.

Sent from my iPhone

On Dec 4, 2017, at 4:02 AM, bishwaG <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the reply. I tried to download from UCSC table browser, but got little lost. Do I select group: Repeatsand track: RepeatMasker?

**Comment by bishwaG** [comment]
I am trying to calculate mappability for GRCh38 by modifying your script  CODEX/mouse/mapp.R. I am wondering what does the file chr22_400_to_500.bed actually contain?

**Comment by yuchaojiang** [comment]
It’s in the vignettes: bed file specifies the genomic locations for exonic targets.

On Dec 14, 2017, at 4:50 AM, bishwaG <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to calculate mappability for GRCh38 by modifying your script CODEX/mouse/mapp.R. I am wondering what does the file chr22_400_to_500.bed actually contain?
